version: '3.1'

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: oauth-mailhog
    ports:
      - '7021:8025'

  redis:
    image: redis:alpine
    container_name: oauth-redis

  mysql:
    image: mysql:8.0
    working_dir: /application
    container_name: oauth-mysql
    volumes:
      - .:/application
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=8wSEWBkwLY
      - MYSQL_DATABASE=oauth
      - MYSQL_USER=oauthUser
      - MYSQL_PASSWORD=8NP1k26Tvk
    ports:
      - '7022:3306'

  webserver:
    image: nginx:alpine
    working_dir: /application
    container_name: oauth-nginx
    depends_on:
      - php-fpm
    volumes:
      - ./backend:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '7020:80'

  php-fpm:
    build: docker/php-fpm
    platform: linux/amd64
    container_name: oauth-php-fpm
    working_dir: /application
    environment:
      XDEBUG_MODE: "coverage"
    security_opt:
      - seccomp=unconfined
    depends_on:
      - mysql
      - redis
      - mailhog
    volumes:
      - ./backend:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini

  node:
    image: node:18
    container_name: oauth-node
    working_dir: /application
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/application
    command: "tail -f /dev/null"
    ports:
      - "5173:5173"
    depends_on:
      - php-fpm

volumes:
  mysql-volume:
